global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ram_server
    static_configs:
      - targets: ['ram-server:8081']
  
  - job_name: ram_microservices
    static_configs:
      - targets: ['ram-microservices:8081']
