version: '3.8'

name: ram-e2e

x-server-build: &server-common
  image: ram-server:latest
  build:
    context: ../
    dockerfile: server/Dockerfile
  environment:
    - DB_HOSTNAME=database
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_DATABASE_NAME=ram
    - ram_MACHINE_LEARNING_ENABLED=false
    - ram_METRICS=true
  volumes:
    - upload:/usr/src/app/upload
    - ./test-assets:/test-assets
  depends_on:
    - redis
    - database

services:
  ram-server:
    container_name: ram-e2e-server
    command: ['./start.sh', 'ram']
    <<: *server-common
    ports:
      - 2283:3001

  ram-microservices:
    container_name: ram-e2e-microservices
    command: ['./start.sh', 'microservices']
    <<: *server-common

  redis:
    image: redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: -c fsync=off -c shared_preload_libraries=vectors.so
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ram
    ports:
      - 5433:5432

volumes:
  model-cache:
  upload:
